import React from 'react'

export const MainLayout = ({ children }) => {
    return (
        <>

            <Head>
                <title>Primera page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <main className={`${styles.main} ${inter.className}`}>
                { children }
            </main>

        </>
    )
}
