import Head from 'next/head'
import { Navbar } from '../ui'
import React from 'react'
import styles from '../../styles/Home.module.css'

export const MainLayout = ({ children }) => {
    return (
        <>

            <Head>
                <title>Primera page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <main className={`${styles.main}`}>
                {children}
            </main>

        </>
    )
}
